"""
Dashboard Schema Models for Self-Developing Dashboards.

This module defines the schema format for dynamically generated dashboards.
The schema captures:
- Widget definitions (type, configuration)
- Data bindings (metrics, dimensions, periods)
- Layout positioning (grid-based)
- Interaction rules (drill-down, filters, linked widgets)

The schema is generated by the NLQ backend from natural language requests
and consumed by the frontend to render dynamic dashboards.
"""

from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field


# =============================================================================
# Enums
# =============================================================================

class WidgetType(str, Enum):
    """Available widget types for dashboard composition."""
    LINE_CHART = "line_chart"
    BAR_CHART = "bar_chart"
    HORIZONTAL_BAR = "horizontal_bar"
    STACKED_BAR = "stacked_bar"
    DONUT_CHART = "donut_chart"
    AREA_CHART = "area_chart"
    KPI_CARD = "kpi_card"
    DATA_TABLE = "data_table"
    SPARKLINE = "sparkline"
    FILTER_CONTROL = "filter_control"
    TIME_RANGE_SELECTOR = "time_range_selector"
    TEXT_BLOCK = "text_block"
    MAP = "map"


class AggregationType(str, Enum):
    """Aggregation methods for data series."""
    SUM = "sum"
    AVERAGE = "average"
    MIN = "min"
    MAX = "max"
    COUNT = "count"
    LAST = "last"
    FIRST = "first"


class TimeGranularity(str, Enum):
    """Time granularity for trend data."""
    DAILY = "daily"
    WEEKLY = "weekly"
    MONTHLY = "monthly"
    QUARTERLY = "quarterly"
    YEARLY = "yearly"


class InteractionType(str, Enum):
    """Types of widget interactions."""
    DRILL_DOWN = "drill_down"
    FILTER = "filter"
    HIGHLIGHT = "highlight"
    TOOLTIP = "tooltip"
    NAVIGATE = "navigate"


class ComparisonType(str, Enum):
    """Types of period comparisons."""
    PRIOR_PERIOD = "prior_period"
    PRIOR_YEAR = "prior_year"
    BUDGET = "budget"
    TARGET = "target"
    CUSTOM = "custom"


# =============================================================================
# Data Binding Models
# =============================================================================

class MetricBinding(BaseModel):
    """Binds a widget to a specific metric from the fact base."""

    metric: str = Field(..., description="Canonical metric name (e.g., 'revenue', 'gross_margin_pct')")
    alias: Optional[str] = Field(default=None, description="Display name override")
    aggregation: AggregationType = Field(default=AggregationType.LAST, description="How to aggregate multiple values")
    format: Optional[str] = Field(default=None, description="Format string (e.g., '$0.0M', '0.0%')")
    color: Optional[str] = Field(default=None, description="Color for this metric in visualizations")


class DimensionBinding(BaseModel):
    """Binds a widget to a dimension for grouping/breakdown."""

    dimension: str = Field(..., description="Dimension field (e.g., 'region', 'product', 'rep')")
    alias: Optional[str] = Field(default=None, description="Display name override")
    sort_by: Optional[str] = Field(default=None, description="Field to sort by ('value', 'name', metric name)")
    sort_order: str = Field(default="desc", description="Sort order ('asc' or 'desc')")
    limit: Optional[int] = Field(default=None, description="Limit number of dimension values")


class TimeBinding(BaseModel):
    """Binds a widget to a time range and granularity."""

    period: str = Field(..., description="Time period (e.g., '2025', 'Q4 2025', 'last 12 months')")
    granularity: TimeGranularity = Field(default=TimeGranularity.QUARTERLY, description="Time granularity for trends")
    comparison: Optional[ComparisonType] = Field(default=None, description="Period comparison type")
    comparison_period: Optional[str] = Field(default=None, description="Specific comparison period if custom")


class DataBinding(BaseModel):
    """Complete data binding configuration for a widget."""

    metrics: List[MetricBinding] = Field(default_factory=list, description="Metrics to display")
    dimensions: List[DimensionBinding] = Field(default_factory=list, description="Dimensions for grouping")
    time: Optional[TimeBinding] = Field(default=None, description="Time configuration")
    filters: Dict[str, Any] = Field(default_factory=dict, description="Static filters to apply")


# =============================================================================
# Widget Configuration Models
# =============================================================================

class ChartConfig(BaseModel):
    """Configuration specific to chart widgets."""

    show_legend: bool = Field(default=True, description="Whether to show chart legend")
    show_grid: bool = Field(default=True, description="Whether to show grid lines")
    show_labels: bool = Field(default=False, description="Whether to show data labels on points")
    stacked: bool = Field(default=False, description="Whether to stack series (for bar/area)")
    show_trend_line: bool = Field(default=False, description="Whether to show trend line")
    animate: bool = Field(default=True, description="Whether to animate on load")
    color_palette: Optional[List[str]] = Field(default=None, description="Custom color palette")


class KPIConfig(BaseModel):
    """Configuration specific to KPI card widgets."""

    show_trend: bool = Field(default=True, description="Whether to show trend indicator")
    show_sparkline: bool = Field(default=False, description="Whether to show mini sparkline")
    trend_period: str = Field(default="prior_period", description="Period for trend calculation")
    thresholds: Optional[Dict[str, float]] = Field(default=None, description="Threshold values for status colors")
    inverse_status: bool = Field(default=False, description="Whether lower is better (e.g., churn)")


class TableConfig(BaseModel):
    """Configuration specific to table widgets."""

    show_totals: bool = Field(default=False, description="Whether to show totals row")
    sortable: bool = Field(default=True, description="Whether columns are sortable")
    paginated: bool = Field(default=False, description="Whether to paginate")
    page_size: int = Field(default=10, description="Rows per page if paginated")
    row_click_action: Optional[str] = Field(default=None, description="Action on row click")


class FilterConfig(BaseModel):
    """Configuration specific to filter control widgets."""

    filter_type: str = Field(default="dropdown", description="Filter UI type ('dropdown', 'checkbox', 'range')")
    multi_select: bool = Field(default=False, description="Whether to allow multiple selections")
    show_all_option: bool = Field(default=True, description="Whether to show 'All' option")
    linked_widgets: List[str] = Field(default_factory=list, description="Widget IDs this filter affects")


# =============================================================================
# Interaction Models
# =============================================================================

class DrillDownConfig(BaseModel):
    """Configuration for drill-down interaction."""

    target_dimension: str = Field(..., description="Dimension to drill into")
    query_template: str = Field(..., description="NLQ query template with {value} placeholder")


class FilterPropagation(BaseModel):
    """Configuration for filter propagation between widgets."""

    source_widget: str = Field(..., description="Widget ID that triggers the filter")
    target_widgets: List[str] = Field(..., description="Widget IDs that receive the filter")
    dimension: str = Field(..., description="Dimension being filtered")


class InteractionConfig(BaseModel):
    """Interaction configuration for a widget."""

    type: InteractionType = Field(..., description="Type of interaction")
    enabled: bool = Field(default=True, description="Whether interaction is enabled")
    drill_down: Optional[DrillDownConfig] = Field(default=None, description="Drill-down config if type is DRILL_DOWN")
    filter_propagation: Optional[FilterPropagation] = Field(default=None, description="Filter config if type is FILTER")


# =============================================================================
# Layout Models
# =============================================================================

class GridPosition(BaseModel):
    """Position of a widget in the grid layout."""

    column: int = Field(..., ge=1, le=12, description="Start column (1-12)")
    row: int = Field(..., ge=1, description="Start row (1-based)")
    col_span: int = Field(default=4, ge=1, le=12, description="Number of columns to span")
    row_span: int = Field(default=2, ge=1, description="Number of rows to span")


class LayoutConfig(BaseModel):
    """Overall layout configuration for the dashboard."""

    columns: int = Field(default=12, description="Number of grid columns")
    row_height: int = Field(default=80, description="Height of each row in pixels")
    gap: int = Field(default=16, description="Gap between widgets in pixels")
    padding: int = Field(default=24, description="Dashboard padding in pixels")


# =============================================================================
# Widget Model
# =============================================================================

class Widget(BaseModel):
    """A single widget in the dashboard."""

    id: str = Field(..., description="Unique widget identifier")
    type: WidgetType = Field(..., description="Widget type")
    title: str = Field(..., description="Widget title/header")
    description: Optional[str] = Field(default=None, description="Optional description")

    # Data binding
    data: DataBinding = Field(..., description="Data binding configuration")

    # Position
    position: GridPosition = Field(..., description="Grid position")

    # Type-specific configuration
    chart_config: Optional[ChartConfig] = Field(default=None, description="Chart-specific config")
    kpi_config: Optional[KPIConfig] = Field(default=None, description="KPI-specific config")
    table_config: Optional[TableConfig] = Field(default=None, description="Table-specific config")
    filter_config: Optional[FilterConfig] = Field(default=None, description="Filter-specific config")

    # Interactions
    interactions: List[InteractionConfig] = Field(default_factory=list, description="Widget interactions")

    # Styling
    style: Dict[str, Any] = Field(default_factory=dict, description="Custom CSS styles")


# =============================================================================
# Dashboard Schema Model
# =============================================================================

class DashboardSchema(BaseModel):
    """
    Complete dashboard schema generated from natural language.

    This schema is:
    - Generated by the NLQ backend from user requests
    - Consumed by the frontend to render dynamic dashboards
    - Mutable through conversational refinement
    """

    # Identity
    id: str = Field(..., description="Unique dashboard identifier")
    title: str = Field(..., description="Dashboard title")
    description: Optional[str] = Field(default=None, description="Dashboard description")

    # Source query
    source_query: str = Field(..., description="Original NL query that generated this dashboard")

    # Layout
    layout: LayoutConfig = Field(default_factory=LayoutConfig, description="Layout configuration")

    # Widgets
    widgets: List[Widget] = Field(default_factory=list, description="Dashboard widgets")

    # Global settings
    time_range: Optional[TimeBinding] = Field(default=None, description="Global time range")
    refresh_interval: int = Field(default=0, description="Auto-refresh interval in seconds (0 = disabled)")

    # Metadata
    confidence: float = Field(default=0.8, ge=0.0, le=1.0, description="Confidence in schema generation")
    version: int = Field(default=1, description="Schema version for tracking refinements")

    # Conversation context
    conversation_id: Optional[str] = Field(default=None, description="Conversation ID for refinement")
    refinement_history: List[str] = Field(default_factory=list, description="History of refinement queries")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "id": "dash_revenue_by_region",
                "title": "Revenue by Region",
                "description": "Revenue breakdown by geographic region over time",
                "source_query": "Show me revenue by region over time",
                "layout": {
                    "columns": 12,
                    "row_height": 80,
                    "gap": 16,
                    "padding": 24
                },
                "widgets": [
                    {
                        "id": "total_revenue_kpi",
                        "type": "kpi_card",
                        "title": "Total Revenue",
                        "data": {
                            "metrics": [{"metric": "revenue", "format": "$0.0M"}],
                            "time": {"period": "2025", "granularity": "yearly"}
                        },
                        "position": {"column": 1, "row": 1, "col_span": 3, "row_span": 2},
                        "kpi_config": {"show_trend": True, "show_sparkline": True}
                    },
                    {
                        "id": "revenue_by_region_chart",
                        "type": "bar_chart",
                        "title": "Revenue by Region",
                        "data": {
                            "metrics": [{"metric": "revenue", "format": "$0.0M"}],
                            "dimensions": [{"dimension": "region"}],
                            "time": {"period": "2025", "granularity": "yearly"}
                        },
                        "position": {"column": 4, "row": 1, "col_span": 9, "row_span": 4},
                        "chart_config": {"show_legend": True},
                        "interactions": [
                            {
                                "type": "drill_down",
                                "enabled": True,
                                "drill_down": {
                                    "target_dimension": "rep",
                                    "query_template": "Show me revenue for {value} region by rep"
                                }
                            }
                        ]
                    }
                ],
                "time_range": {"period": "2025", "granularity": "quarterly"},
                "confidence": 0.92,
                "version": 1
            }
        }
    )


# =============================================================================
# Response Models
# =============================================================================

class DashboardGenerationResponse(BaseModel):
    """Response from dashboard generation endpoint."""

    success: bool = Field(..., description="Whether generation succeeded")
    dashboard: Optional[DashboardSchema] = Field(default=None, description="Generated dashboard schema")
    widget_data: Optional[Dict[str, Any]] = Field(default=None, description="Pre-resolved widget data from fact base")
    error: Optional[str] = Field(default=None, description="Error message if failed")

    # Generation metadata
    query: str = Field(..., description="Original query")
    intent_detected: str = Field(..., description="Detected visualization intent")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Generation confidence")

    # Suggestions for refinement
    suggestions: List[str] = Field(default_factory=list, description="Suggested follow-up queries")


class DashboardRefinementRequest(BaseModel):

    dashboard_id: str = Field(..., description="ID of dashboard to refine")
    refinement_query: str = Field(..., description="Natural language refinement request")
    conversation_id: Optional[str] = Field(default=None, description="Conversation ID for context")
    data_mode: Optional[str] = Field(default=None, description="Data mode: 'live' for DCL, 'demo' for local fact_base.json")


class DashboardRefinementResponse(BaseModel):
    """Response from dashboard refinement endpoint."""

    success: bool = Field(..., description="Whether refinement succeeded")
    dashboard: Optional[DashboardSchema] = Field(default=None, description="Updated dashboard schema")
    widget_data: Optional[Dict[str, Any]] = Field(default=None, description="Pre-resolved widget data from fact base")
    error: Optional[str] = Field(default=None, description="Error message if failed")
    refinement_status: str = Field(default="applied", description="Refinement outcome: applied, noop, or error")
    noop_reason: Optional[str] = Field(default=None, description="Reason for no-op if status is noop")

    changes_made: List[str] = Field(default_factory=list, description="Summary of changes made")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Refinement confidence")
